---
- name: Set Account Lockout Policy
  hosts: all
  become: yes

  tasks:
    - name: Set Account Lockout Policy for RHEL
      ansible.builtin.command: >
        faillock --unlock-time 900 --lock-time 1800 --reset --maximum 3
      when: "'RedHat' in ansible_distribution"

    - name: Set Account Lockout Policy for Ubuntu
      ansible.builtin.command: >
        pam_tally2 --deny=3 --noreset
      when: "'Ubuntu' in ansible_distribution"

    - name: Set Account Lockout Policy for Windows
      ansible.windows.win_account_policy:
        lockout_threshold: 3
        lockout_duration_minutes: 15
        lockout_observation_window_minutes: 15
      when: "'Microsoft' in ansible_distribution"

