---
# Add multiple users into wheel group and create random passwords for users which should be changed after one-time login
- name: Create users
  hosts: all
  become: true
  vars:
    users:
      - user1
      - user2
      # Add more users as needed
    password_dict: {}

  tasks:
    - name: Install the latest version of whois (provides mkpasswd)
      ansible.builtin.package:
        name: whois
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install the latest version of expect
      ansible.builtin.package:
        name: expect
        state: latest
      when: ansible_distribution == 'RedHat'

    - name: Create the 'wheel' group if it does not exist
      ansible.builtin.group:
        name: wheel
        state: present

    - name: Generate random passwords for users
      ansible.builtin.command: mkpasswd -m sha-512 --chars=12
      register: encrypted_user_password
      loop: "{{ users }}"

    - name: Create password dictionary
      set_fact:
        password_dict: "{{ password_dict | combine({item.item: item.stdout_lines[0]}) }}"
      loop: "{{ encrypted_user_password.results }}"

    - name: Create user accounts
      ansible.builtin.user:
        name: "{{ item }}"
        password: "{{ password_dict[item] | password_hash('sha512') }}"
        state: present
        group: wheel
        append: yes
        shell: /bin/bash
        update_password: always
      loop: "{{ users }}"
      register: user_created

    - name: Force users to change passwords on first login
      ansible.builtin.command:
        cmd: chage -d 0 {{ item.item }}
      loop: "{{ user_created.results }}"
      when: item.changed

    - name: Display user names and passwords
      ansible.builtin.debug:
        msg: "User: {{ item.item }} Password: {{ password_dict[item.item] }}"
      loop: "{{ user_created.results }}"


