---
- name: Install Development Tools on Windows using Command
  hosts: all
  gather_facts: true
  tasks:
    - name: Install Git via Chocolatey
      ansible.builtin.win_command: choco install git -y

    - name: Install Node.js via Chocolatey
      ansible.builtin.win_command: choco install nodejs -y

    - name: Install Yarn via Chocolatey
      ansible.builtin.win_command: choco install yarn -y

    # Add more commands for additional packages as needed

    # Add more tasks as needed for additional configurations or checks
