---
- name: Install Standard Applications on Windows using Chocolatey
  hosts: all
  gather_facts: true
  tasks:
    - name: Install Standard Applications via Chocolatey
      win_chocolatey:
        name: "{{ item }}"
        state: present
      with_items:
        - googlechrome
        - vscode
        - firefox
        # Add more applications as needed

    # Add more tasks as needed for additional configurations or checks


