---
- name: Rollback Configuration on Linux Servers
  hosts: all
  become: true
  tasks:
    - name: Check if backup files exist
      stat:
        path: /etc/nginx/nginx.conf
      register: backup_files

    - name: Rollback configuration files
      ansible.builtin.copy:
        src: /etc/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf_bkp.$(date +%Y_%m_%d_%H_%M_%S)
        remote_src: yes
      when: backup_files.stat.exists

