---
- name: Delete Multiple Windows Users
  hosts: windows
  gather_facts: true

  vars:
    users_to_delete:
      - "user1"
      - "user2"
      - "user3"

  tasks:
    - name: Delete Windows Users
      ansible.builtin.win_user:
        name: "{{ item }}"
        state: absent
      with_items: "{{ users_to_delete }}"

  handlers:
    - name: restart winrm
      ansible.builtin.win_shell: Restart-Service WinRM
      async: 45
      poll: 0