---
- name: install_linux_package
  hosts: all
  gather_facts: true
  become: true

  tasks:

    - name: Install packages
      ansible.builtin.package:
        name:
          - "apache2"
          - "wget"
        state: present
