---
- name: Remove Specific Packages
  hosts: all
  gather_facts: true

  tasks:
    - name: Remove Apache Web Server and MySQL Database Server
      ansible.builtin.package:
        name: 
          - "apache2" 
          - "mysql-server"
        state: absent
