---
- name: Add Multiple Windows Users
  hosts: win
  gather_facts: true

  vars:
    ansible_user=Administrator
    ansible_password=G!BG2ophdYfVYX.Tw%yXb;ne3F@y=tf%
    ansible_port=5986
    ansible_connection=winrm
    ansible_winrm_scheme=https
    ansible_winrm_server_cert_validation=ignore
    ansible_winrm_kerberos_delegation=true
    users_to_add:
      - username: "user1"
      - username: "user2"
      - username: "user3"

  tasks:
    - name: Create Administrators Group
      ansible.builtin.win_group:
        name: Administrators
        state: present

    - name: Add Windows Users
      ansible.builtin.win_user:
        name: "{{ item.username }}"
        state: present
        groups: "Administrators"
        password_never_expires: yes
      with_items: "{{ users_to_add }}"

  handlers:
    - name: restart winrm
      ansible.builtin.win_shell: Restart-Service WinRM
      async: 45
      poll: 0
