---
- name: Windows Server Pre-Check
  hosts: all
  gather_facts: true
  tasks:
    - name: Display System Information
      win_shell: Get-ComputerInfo
      register: system_info_output

    - name: Display Disk Space Information
      win_shell: Get-Volume | Format-Table -AutoSize
      register: disk_info_output

    - name: Display Network Configuration
      win_shell: Get-NetIPAddress | Format-Table -AutoSize
      register: network_info_output

    - name: Display Installed Software
      win_shell: Get-WmiObject -Class Win32_Product | Select-Object Name, Version
      register: software_info_output

    # Add more tasks as needed for additional pre-checks

    - name: Display Results
      debug:
        var: item.stdout_lines
      loop:
        - "{{ system_info_output }}"
        - "{{ disk_info_output }}"
        - "{{ network_info_output }}"
        - "{{ software_info_output }}"
